services:
  - type: web
    name: embedding-api
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn app:app --host 0.0.0.0 --port $PORT
    autoDeploy: true
    healthCheckPath: /health
    envVars:
      - key: EMBED_MODEL
        value: sentence-transformers/paraphrase-multilingual-MiniLM-L12-v2
      - key: HF_HUB_ENABLE_HF_TRANSFER
        value: "1"
      - key: TRANSFORMERS_CACHE
        value: /tmp/hf
      - key: SENTENCE_TRANSFORMERS_HOME
        value: /tmp/st
      - key: TRANSFORMERS_NO_TF
        value: "1"
      - key: TRANSFORMERS_NO_FLAX
        value: "1"